spring.application.name=deduplicator-service

spring.datasource.url=jdbc:postgresql://localhost:5432/deduplicator
spring.datasource.username=deduplicator
spring.datasource.password=deduplicator
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.threads.virtual.enabled=true

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test
spring.mail.password=test
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false